from __future__ import annotations

from routers.auth import build_auth_router
from routers.clients import build_clients_router
from routers.inbounds import build_inbounds_router
from routers.live_data import build_live_data_router
from routers.monitoring import build_monitoring_router
from routers.nodes import build_nodes_router
from routers.observability import build_observability_router
from routers.operations import build_operations_router
from routers.realtime import build_realtime_router
from routers.subscriptions import build_subscriptions_router


def register_app_routers(
    app,
    *,
    snapshot_collector,
    render_metrics_response,
    deps_health_status,
    check_auth,
    verify_totp_code,
    get_user_role,
    mfa_totp_enabled,
    get_node_or_404,
    get_cached_traffic_stats,
    get_cached_online_clients,
    list_nodes,
    xui_monitor,
    node_service,
    db_path,
    encrypt,
    requests_verify,
    login_panel,
    xui_request,
    invalidate_subscription_cache,
    remove_node_metric_labels,
    node_metric_labels_lock,
    node_metric_labels_state,
    ws_manager,
    logger,
    inbound_mgr,
    invalidate_live_stats_cache,
    client_mgr,
    get_cached_clients,
    check_subscription_rate_limit,
    get_emails,
    get_links_filtered,
    verify_tls_default,
    list_adguard_sources,
    collect_adguard_once,
    adguard_latest,
    adguard_latest_lock,
    adguard_collect_interval_sec,
    build_adguard_summary,
    build_adguard_history,
    parse_basic_auth_pair,
    http_probe,
    prom_query,
    prometheus_url,
    loki_url,
    grafana_url,
    prometheus_basic_auth,
    loki_basic_auth,
    grafana_basic_auth,
    web_path,
    grafana_web_path,
    server_monitor,
    check_basic_auth_header,
    mfa_totp_ws_strict,
    pam_authenticate,
    handle_websocket_message,
):
    app.include_router(
        build_observability_router(
            get_latest_snapshot=snapshot_collector.latest_snapshot,
            render_metrics=render_metrics_response,
            get_deps_health=deps_health_status,
        )
    )
    app.include_router(
        build_auth_router(
            check_auth=check_auth,
            verify_totp_code=verify_totp_code,
            get_user_role=get_user_role,
            mfa_totp_enabled=mfa_totp_enabled,
        )
    )
    app.include_router(
        build_live_data_router(
            get_node_or_404=get_node_or_404,
            get_cached_traffic_stats=get_cached_traffic_stats,
            get_cached_online_clients=get_cached_online_clients,
            list_nodes=list_nodes,
            xui_monitor=xui_monitor,
        )
    )
    app.include_router(
        build_nodes_router(
            check_auth=check_auth,
            node_service=node_service,
            db_path=db_path,
            encrypt=encrypt,
            requests_verify=requests_verify,
            login_panel=login_panel,
            xui_request=xui_request,
            invalidate_subscription_cache=invalidate_subscription_cache,
            remove_node_metric_labels=remove_node_metric_labels,
            node_metric_labels_lock=node_metric_labels_lock,
            node_metric_labels_state=node_metric_labels_state,
            snapshot_collector=snapshot_collector,
            ws_manager=ws_manager,
            logger=logger,
        )
    )
    app.include_router(
        build_inbounds_router(
            check_auth=check_auth,
            inbound_mgr=inbound_mgr,
            node_service=node_service,
            get_node_or_404=get_node_or_404,
            invalidate_subscription_cache=invalidate_subscription_cache,
            invalidate_live_stats_cache=invalidate_live_stats_cache,
            ws_manager=ws_manager,
        )
    )
    app.include_router(
        build_clients_router(
            check_auth=check_auth,
            client_mgr=client_mgr,
            get_cached_clients=get_cached_clients,
            node_service=node_service,
            get_node_or_404=get_node_or_404,
            invalidate_live_stats_cache=invalidate_live_stats_cache,
            invalidate_subscription_cache=invalidate_subscription_cache,
        )
    )
    app.include_router(
        build_subscriptions_router(
            check_auth=check_auth,
            db_path=db_path,
            node_service=node_service,
            check_subscription_rate_limit=check_subscription_rate_limit,
            get_emails=get_emails,
            get_links_filtered=get_links_filtered,
            invalidate_subscription_cache=invalidate_subscription_cache,
            logger=logger,
        )
    )
    app.include_router(
        build_monitoring_router(
            check_auth=check_auth,
            db_path=db_path,
            verify_tls_default=verify_tls_default,
            encrypt=encrypt,
            list_adguard_sources=list_adguard_sources,
            collect_adguard_once=collect_adguard_once,
            adguard_latest=adguard_latest,
            adguard_latest_lock=adguard_latest_lock,
            adguard_collect_interval_sec=adguard_collect_interval_sec,
            build_adguard_summary=build_adguard_summary,
            build_adguard_history=build_adguard_history,
            parse_basic_auth_pair=parse_basic_auth_pair,
            http_probe=http_probe,
            prom_query=prom_query,
            prometheus_url=prometheus_url,
            loki_url=loki_url,
            grafana_url=grafana_url,
            prometheus_basic_auth=prometheus_basic_auth,
            loki_basic_auth=loki_basic_auth,
            grafana_basic_auth=grafana_basic_auth,
            web_path=web_path,
            grafana_web_path=grafana_web_path,
        )
    )
    app.include_router(
        build_operations_router(
            check_auth=check_auth,
            db_path=db_path,
            node_service=node_service,
            client_mgr=client_mgr,
            server_monitor=server_monitor,
            get_node_or_404=get_node_or_404,
        )
    )
    app.include_router(
        build_realtime_router(
            check_basic_auth_header=check_basic_auth_header,
            verify_totp_code=verify_totp_code,
            mfa_totp_ws_strict=mfa_totp_ws_strict,
            pam_authenticate=pam_authenticate,
            ws_manager=ws_manager,
            handle_websocket_message=handle_websocket_message,
            logger=logger,
        )
    )
