"""
Модуль управления инбаундами node panel
Содержит функции для получения, создания, клонирования и удаления инбаундов
"""
import requests
import json
import logging
import sys
import os
import copy
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
from typing import List, Dict, Optional

sys.path.insert(0, str(Path(__file__).parent))
from xui_session import XUI_FAST_RETRIES, XUI_FAST_TIMEOUT_SEC, extract_node_auth, login_panel, xui_request
from utils import parse_field_as_dict

logger = logging.getLogger("sub_manager")
VERIFY_TLS = os.getenv("VERIFY_TLS", "true").strip().lower() in ("1", "true", "yes", "on")
CA_BUNDLE_PATH = os.getenv("CA_BUNDLE_PATH", "").strip()
INBOUND_MAX_WORKERS = max(1, int(os.getenv("INBOUND_MAX_WORKERS", "8")))

_shared_executor = ThreadPoolExecutor(max_workers=INBOUND_MAX_WORKERS, thread_name_prefix="inbound_mgr")

_NESTED_INBOUND_FIELDS = frozenset({"settings", "streamSettings", "sniffing", "allocate"})

# These values describe the row returned by the panel, not configuration that
# can be submitted again when creating a new inbound.  In particular, keeping
# ``tag`` or ``id`` makes a cloned inbound collide with its source, and traffic
# statistics must never be copied as configuration.
_CLONE_SERVER_OWNED_FIELDS = frozenset({
    "id",
    "clientStats",
    "up",
    "down",
    "lastTrafficResetTime",
    "tag",
    "nodeId",
    "originNodeGuid",
    "fallbackParent",
})


def _requests_verify_value():
    if not VERIFY_TLS:
        return False
    if CA_BUNDLE_PATH:
        return CA_BUNDLE_PATH
    return True


def _decode_inbound_object(value):
    """Return a detached nested inbound object, accepting v3 object/string forms."""
    if isinstance(value, dict):
        return copy.deepcopy(value)
    if isinstance(value, str):
        try:
            decoded = json.loads(value)
        except (TypeError, ValueError):
            return None
        if isinstance(decoded, dict):
            return decoded
    return None


def _deep_merge_inbound_object(current: Dict, updates: Dict) -> Dict:
    """Overlay recognised edits without dropping future nested 3x-ui fields."""
    merged = copy.deepcopy(current)
    for key, value in updates.items():
        if isinstance(value, dict) and isinstance(merged.get(key), dict):
            merged[key] = _deep_merge_inbound_object(merged[key], value)
        else:
            merged[key] = copy.deepcopy(value)
    return merged


def _clear_inbound_clients(value, *, node_name: str):
    """Remove clients without changing whether a panel returned JSON or text."""
    settings = _decode_inbound_object(value)
    if settings is None:
        raise ValueError(f"Cannot safely clone inbound with unreadable settings on {node_name}")

    settings["clients"] = []
    return json.dumps(settings, ensure_ascii=False) if isinstance(value, str) else settings


def _clone_inbound_payload(source: Dict, modifications: Optional[Dict], *, node_name: str) -> Dict:
    """Create an add payload from the complete source DTO without shared state.

    New 3x-ui releases add inbound fields regularly.  Starting from the whole
    source record avoids silently dropping those fields, while stripping only
    values generated by the source panel before applying explicit operator
    modifications.
    """
    payload = copy.deepcopy(source)
    for field in _CLONE_SERVER_OWNED_FIELDS:
        payload.pop(field, None)

    changes = copy.deepcopy(modifications or {})
    include_clients = bool(changes.pop("include_clients", False))
    for field in _CLONE_SERVER_OWNED_FIELDS:
        changes.pop(field, None)
    if not include_clients:
        payload["settings"] = _clear_inbound_clients(payload.get("settings"), node_name=node_name)

    payload.update(changes)
    return payload


class InboundManager:
    def __init__(self, decrypt_func, encrypt_func=None):
        """Инициализация менеджера инбаундов с функциями шифрования/дешифрования
        
        Args:
            decrypt_func: Функция для расшифровки паролей узлов
            encrypt_func: Опциональная функция для шифрования паролей
        """
        self.decrypt = decrypt_func
        self.encrypt = encrypt_func

    @staticmethod
    def _is_read_only(node: Dict) -> bool:
        return bool(node.get("read_only"))

    @staticmethod
    def _merge_inbound_updates(current: Dict, updates: Dict) -> Dict:
        """Prepare a full v3 update payload while retaining unknown nested fields.

        The current 3x-ui update endpoint replaces an inbound rather than
        applying a JSON patch.  Preserve any current fields we do not own,
        including newer XHTTP and Reality settings, before applying a partial
        control-plane update.
        """
        payload = copy.deepcopy(current)
        for key, value in updates.items():
            if key not in _NESTED_INBOUND_FIELDS:
                payload[key] = copy.deepcopy(value)
                continue

            current_object = _decode_inbound_object(payload.get(key))
            update_object = _decode_inbound_object(value)
            if current_object is None or update_object is None:
                # An explicit scalar/invalid replacement remains the caller's
                # responsibility; do not silently manufacture configuration.
                payload[key] = copy.deepcopy(value)
                continue

            merged = _deep_merge_inbound_object(current_object, update_object)
            # Keep the remote representation stable.  Current 3x-ui accepts
            # both forms, while older panels commonly return JSON strings.
            payload[key] = json.dumps(merged, ensure_ascii=False) if isinstance(payload.get(key), str) else merged

        return payload
    
    def get_all_inbounds(self, nodes: List[Dict]) -> List[Dict]:
        """Получить все инбаунды со всех узлов
        
        Args:
            nodes: Список узлов с конфигурацией
            
        Returns:
            Список инбаундов с метаданными
        """
        def _collect_node_inbounds(node: Dict) -> List[Dict]:
            collected: List[Dict] = []
            try:
                node_inbounds = self._fetch_inbounds_from_node(node)
                for ib in node_inbounds:
                    stream = parse_field_as_dict(
                        ib.get("streamSettings"),
                        node_id=node["name"],
                        field_name="streamSettings",
                    )
                    raw_settings = parse_field_as_dict(
                        ib.get("settings"),
                        node_id=node["name"],
                        field_name="settings",
                    )
                    # Count clients before stripping them from settings
                    client_count = len(raw_settings.get("clients", []))
                    inbound = {
                        "id": ib.get("id"),
                        "node_name": node["name"],
                        "node_ip": node["ip"],
                        "protocol": ib.get("protocol"),
                        "port": ib.get("port"),
                        "remark": ib.get("remark", ""),
                        "enable": ib.get("enable", True),
                        # Keep these in their panel-provided form.  The edit
                        # UI must not turn an unrelated remark/port change
                        # into an empty bind address or default sniffing.
                        "listen": ib.get("listen", ""),
                        "sniffing": copy.deepcopy(ib.get("sniffing")),
                        "client_count": client_count,
                        "streamSettings": stream,
                        "settings": raw_settings,
                    }
                    security = stream.get("security", "")
                    inbound["security"] = security
                    inbound["is_reality"] = security == "reality"
                    collected.append(inbound)
            except Exception as exc:
                logger.warning(f"Failed to fetch inbounds from {node['name']}: {exc}")
            return collected

        inbounds: List[Dict] = []
        futures = [_shared_executor.submit(_collect_node_inbounds, node) for node in nodes]
        for future in as_completed(futures):
            try:
                inbounds.extend(future.result())
            except Exception as exc:
                logger.warning(f"Failed to aggregate inbounds: {exc}")

        return inbounds
    
    def _fetch_inbounds_from_node(self, node: Dict) -> List[Dict]:
        """Получить инбаунды с конкретного узла"""
        s = requests.Session()
        s.verify = _requests_verify_value()
        b_path = node.get("base_path", "").strip("/")
        prefix = f"/{b_path}" if b_path else ""
        scheme = node.get("scheme", "https")
        base_url = f"{scheme}://{node['ip']}:{node['port']}{prefix}"
        
        try:
            username, password, bearer_token = extract_node_auth(node, self.decrypt)
            if not login_panel(
                s,
                base_url,
                username,
                password,
                bearer_token=bearer_token,
                timeout=XUI_FAST_TIMEOUT_SEC,
                retries=XUI_FAST_RETRIES,
            ):
                logger.warning(f"node panel login failed for node {node['name']}")
                return []
            res = xui_request(
                s,
                "GET",
                f"{base_url}/panel/api/inbounds/list",
                timeout=XUI_FAST_TIMEOUT_SEC,
                retries=XUI_FAST_RETRIES,
            )
            if res.status_code == 200:
                data = res.json()
                return data.get("obj", []) if data.get("success", False) else []
            logger.warning(
                f"node panel {node['name']} inbounds list returned status {res.status_code}; "
                f"response (first 200 chars): {res.text[:200]!r}"
            )
        except Exception as exc:
            logger.warning(f"Request failed for {node['name']}: {exc}")
        
        return []
    
    def add_inbound(self, node: Dict, config: Dict) -> bool:
        if self._is_read_only(node):
            logger.info(f"Skip add inbound on read-only node {node['name']}")
            return False
        """Добавить инбаунд на узел
        
        Args:
            node: Конфигурация узла
            config: Конфигурация инбаунда
            
        Returns:
            True при успехе
        """
        s = requests.Session()
        s.verify = _requests_verify_value()
        b_path = node.get("base_path", "").strip("/")
        prefix = f"/{b_path}" if b_path else ""
        scheme = node.get("scheme", "https")
        base_url = f"{scheme}://{node['ip']}:{node['port']}{prefix}"
        
        try:
            username, password, bearer_token = extract_node_auth(node, self.decrypt)
            if not login_panel(s, base_url, username, password, bearer_token=bearer_token):
                logger.warning(f"node panel login failed for node {node['name']}")
                return False
            res = xui_request(
                s,
                "POST",
                f"{base_url}/panel/api/inbounds/add",
                json=config,
            )
            return self._xui_success(res)
        except Exception as exc:
            logger.warning(f"Failed to add inbound to {node['name']}: {exc}")
            return False
    
    def clone_inbound(self, source_node: Dict, source_inbound_id: int, 
                     target_nodes: List[Dict], modifications: Optional[Dict] = None) -> Dict:
        """Клонировать инбаунд с одного узла на другие
        
        Args:
            source_node: Узел-источник инбаунда
            source_inbound_id: ID инбаунда-источника
            target_nodes: Список целевых узлов
            modifications: Опциональные модификации (remark, port и т.д.)
            
        Returns:
            Результаты клонирования по узлам
        """
        # Получить исходный инбаунд
        inbounds = self._fetch_inbounds_from_node(source_node)
        source_inbound = next((ib for ib in inbounds if ib.get('id') == source_inbound_id), None)
        
        if not source_inbound:
            return {"error": "Source inbound not found"}
        
        try:
            new_config = _clone_inbound_payload(
                source_inbound,
                modifications,
                node_name=source_node["name"],
            )
        except ValueError as exc:
            logger.warning("Cannot clone inbound %s on %s: %s", source_inbound_id, source_node["name"], exc)
            return {"error": str(exc)}
        
        results = []
        for target_node in target_nodes:
            if self._is_read_only(target_node):
                results.append({
                    "node": target_node["name"],
                    "success": False,
                    "port": new_config["port"],
                    "remark": new_config["remark"],
                    "error": "Node is read-only",
                })
                continue
            # add_inbound is an external boundary.  Do not let a future
            # normalizer or request hook mutate the template used for the
            # next target node.
            success = self.add_inbound(target_node, copy.deepcopy(new_config))
            results.append({
                "node": target_node["name"],
                "success": success,
                "port": new_config["port"],
                "remark": new_config["remark"]
            })
        
        return {"results": results}
    
    def delete_inbound(self, node: Dict, inbound_id: int) -> bool:
        if self._is_read_only(node):
            logger.info(f"Skip delete inbound on read-only node {node['name']}")
            return False
        """Удалить инбаунд с узла"""
        s = requests.Session()
        s.verify = _requests_verify_value()
        b_path = node.get("base_path", "").strip("/")
        prefix = f"/{b_path}" if b_path else ""
        scheme = node.get("scheme", "https")
        base_url = f"{scheme}://{node['ip']}:{node['port']}{prefix}"
        
        try:
            username, password, bearer_token = extract_node_auth(node, self.decrypt)
            if not login_panel(s, base_url, username, password, bearer_token=bearer_token):
                logger.warning(f"node panel login failed for node {node['name']}")
                return False
            res = xui_request(
                s,
                "POST",
                f"{base_url}/panel/api/inbounds/del/{inbound_id}",
            )
            return self._xui_success(res)
        except Exception as exc:
            logger.warning(f"Failed to delete inbound from {node['name']}: {exc}")
            return False
    
    
    def update_inbound(self, node: Dict, inbound_id: int, updates: Dict) -> bool:
        if self._is_read_only(node):
            logger.info(f"Skip update inbound on read-only node {node['name']}")
            return False
        """Обновить параметры инбаунда
        
        Args:
            node: Конфигурация узла
            inbound_id: ID инбаунда
            updates: Обновления (enable, remark, settings и т.д.)
            
        Returns:
            True при успехе
        """
        s = requests.Session()
        s.verify = _requests_verify_value()
        b_path = node.get("base_path", "").strip("/")
        prefix = f"/{b_path}" if b_path else ""
        scheme = node.get("scheme", "https")
        base_url = f"{scheme}://{node['ip']}:{node['port']}{prefix}"
        
        try:
            username, password, bearer_token = extract_node_auth(node, self.decrypt)
            if not login_panel(s, base_url, username, password, bearer_token=bearer_token):
                logger.warning(f"node panel login failed for node {node['name']}")
                return False

            # Получить текущую конфигурацию инбаунда
            inbounds = self._fetch_inbounds_from_node(node)
            current = next((ib for ib in inbounds if ib.get('id') == inbound_id), None)
            
            if not current:
                logger.warning(f"Inbound {inbound_id} not found on {node['name']}")
                return False
            
            # v3 replaces the inbound payload.  A shallow ``dict.update``
            # loses unmodelled XHTTP/Reality fields when the UI edits only one
            # nested property, so merge the partial edit into the remote DTO.
            payload = self._merge_inbound_updates(current, updates)
            
            res = xui_request(
                s,
                "POST",
                f"{base_url}/panel/api/inbounds/update/{inbound_id}",
                json=payload,
            )
            return self._xui_success(res)
        except Exception as exc:
            logger.warning(f"Failed to update inbound on {node['name']}: {exc}")
            return False
    
    def batch_enable_inbounds(self, nodes: List[Dict], inbound_ids: List[int], enable: bool) -> Dict:
        """Включить/выключить несколько инбаундов
        
        Args:
            nodes: Список узлов
            inbound_ids: Список ID инбаундов
            enable: True для включения, False для выключения
            
        Returns:
            Результаты операции
        """
        results = []
        for node in nodes:
            node_inbounds = self._fetch_inbounds_from_node(node)
            for inbound in node_inbounds:
                if inbound.get('id') in inbound_ids:
                    # Используем быстрый setEnable вместо полного update
                    success = self.set_inbound_enable(node, inbound['id'], enable)
                    results.append({
                        "node": node["name"],
                        "inbound_id": inbound['id'],
                        "remark": inbound.get('remark', ''),
                        "success": success,
                        "enabled": enable
                    })

        return {
            "results": results,
            "total": len(results),
            "successful": sum(1 for r in results if r['success'])
        }
    
    def batch_update_inbounds(self, nodes: List[Dict], inbound_ids: List[int], updates: Dict) -> Dict:
        """Массово обновить несколько инбаундов
        
        Args:
            nodes: Список узлов
            inbound_ids: Список ID инбаундов
            updates: Обновления для применения
            
        Returns:
            Результаты операции
        """
        results = []
        for node in nodes:
            node_inbounds = self._fetch_inbounds_from_node(node)
            for inbound in node_inbounds:
                if inbound.get('id') in inbound_ids:
                    success = self.update_inbound(node, inbound['id'], updates)
                    results.append({
                        "node": node["name"],
                        "inbound_id": inbound['id'],
                        "remark": inbound.get('remark', ''),
                        "success": success
                    })
        
        return {
            "results": results,
            "total": len(results),
            "successful": sum(1 for r in results if r['success'])
        }
    
    def batch_delete_inbounds(self, nodes: List[Dict], inbound_ids: List[int]) -> Dict:
        """Массово удалить несколько инбаундов
        
        Args:
            nodes: Список узлов
            inbound_ids: Список ID инбаундов для удаления
            
        Returns:
            Результаты операции
        """
        results = []
        for node in nodes:
            node_inbounds = self._fetch_inbounds_from_node(node)
            for inbound in node_inbounds:
                if inbound.get('id') in inbound_ids:
                    success = self.delete_inbound(node, inbound['id'])
                    results.append({
                        "node": node["name"],
                        "inbound_id": inbound['id'],
                        "remark": inbound.get('remark', ''),
                        "success": success
                    })
        
        return {
            "results": results,
            "total": len(results),
            "successful": sum(1 for r in results if r['success'])
        }
    # ------------------------------------------------------------------
    # v3 / new API operations
    # ------------------------------------------------------------------

    def set_inbound_enable(self, node: Dict, inbound_id: int, enable: bool) -> bool:
        """Включить/выключить инбаунд.

        v3: POST /panel/api/inbounds/setEnable/{id} — один лёгкий запрос.
        v2 fallback: полное обновление через update_inbound.
        """
        if self._is_read_only(node):
            return False
        s = requests.Session()
        s.verify = _requests_verify_value()
        b_path = node.get("base_path", "").strip("/")
        prefix = f"/{b_path}" if b_path else ""
        scheme = node.get("scheme", "https")
        base_url = f"{scheme}://{node['ip']}:{node['port']}{prefix}"
        try:
            username, password, bearer_token = extract_node_auth(node, self.decrypt)
            if not login_panel(s, base_url, username, password, bearer_token=bearer_token):
                return False
            res = xui_request(s, "POST",
                              f"{base_url}/panel/api/inbounds/setEnable/{inbound_id}",
                              json={"enable": enable})
            if res.status_code not in (404, 405):
                return self._xui_success(res)
            # Only an absent modern route may use the full-update adapter.
            # A reachable error can have applied the change already.
            return self.update_inbound(node, inbound_id, {"enable": enable})
        except Exception as exc:
            logger.warning("set_inbound_enable failed for %s: %s", node["name"], exc)
            return False

    def reset_inbound_traffic(self, node: Dict, inbound_id: int) -> bool:
        """Сбросить трафик одного инбаунда."""
        if self._is_read_only(node):
            return False
        s = requests.Session()
        s.verify = _requests_verify_value()
        b_path = node.get("base_path", "").strip("/")
        prefix = f"/{b_path}" if b_path else ""
        scheme = node.get("scheme", "https")
        base_url = f"{scheme}://{node['ip']}:{node['port']}{prefix}"
        try:
            username, password, bearer_token = extract_node_auth(node, self.decrypt)
            if not login_panel(s, base_url, username, password, bearer_token=bearer_token):
                return False
            res = xui_request(s, "POST",
                              f"{base_url}/panel/api/inbounds/{inbound_id}/resetTraffic")
            return self._xui_success(res)
        except Exception as exc:
            logger.warning("reset_inbound_traffic failed for %s: %s", node["name"], exc)
            return False

    def reset_all_inbound_traffics(self, node: Dict) -> bool:
        """Сбросить трафик всех инбаундов на ноде одним запросом."""
        if self._is_read_only(node):
            return False
        s = requests.Session()
        s.verify = _requests_verify_value()
        b_path = node.get("base_path", "").strip("/")
        prefix = f"/{b_path}" if b_path else ""
        scheme = node.get("scheme", "https")
        base_url = f"{scheme}://{node['ip']}:{node['port']}{prefix}"
        try:
            username, password, bearer_token = extract_node_auth(node, self.decrypt)
            if not login_panel(s, base_url, username, password, bearer_token=bearer_token):
                return False
            res = xui_request(s, "POST",
                              f"{base_url}/panel/api/inbounds/resetAllTraffics")
            return self._xui_success(res)
        except Exception as exc:
            logger.warning("reset_all_inbound_traffics failed for %s: %s", node["name"], exc)
            return False

    def del_all_inbound_clients(self, node: Dict, inbound_id: int) -> Dict:
        """Удалить всех клиентов из инбаунда.

        Возвращает {"deleted": N} или {"error": "..."}.
        """
        if self._is_read_only(node):
            return {"error": "read-only node"}
        s = requests.Session()
        s.verify = _requests_verify_value()
        b_path = node.get("base_path", "").strip("/")
        prefix = f"/{b_path}" if b_path else ""
        scheme = node.get("scheme", "https")
        base_url = f"{scheme}://{node['ip']}:{node['port']}{prefix}"
        try:
            username, password, bearer_token = extract_node_auth(node, self.decrypt)
            if not login_panel(s, base_url, username, password, bearer_token=bearer_token):
                return {"error": "login failed"}
            res = xui_request(s, "POST",
                              f"{base_url}/panel/api/inbounds/{inbound_id}/delAllClients")
            if res.status_code == 200:
                data = res.json()
                if data.get("success"):
                    obj = data.get("obj") or {}
                    return {"deleted": obj.get("deleted", 0)}
            return {"error": f"HTTP {res.status_code}"}
        except Exception as exc:
            logger.warning("del_all_inbound_clients failed for %s: %s", node["name"], exc)
            return {"error": str(exc)}

    @staticmethod
    def _xui_success(res) -> bool:
        """Accept only the documented v3 success envelope for mutations."""
        if res.status_code != 200:
            return False
        try:
            data = res.json()
            return isinstance(data, dict) and data.get("success") is True
        except Exception:
            return False
